# Generated by Django 5.0.3 on 2024-03-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urec_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
