# Generated by Django 4.1.2 on 2022-11-30 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urec_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentTicket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time_submission', models.DateTimeField(auto_now_add=True)),
                ('urec_facility', models.CharField(max_length=255)),
                ('location_in_facility', models.CharField(max_length=255)),
                ('activity_causing_injury', models.CharField(max_length=255)),
                ('injury_type', models.CharField(max_length=255)),
                ('injury_description', models.CharField(max_length=1023)),
                ('staff_netid', models.CharField(default='tst123', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='accident',
            name='accident_description',
            field=models.CharField(blank=True, default='some', max_length=255),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accident_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='accident',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AccidentTicketContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_relation', models.CharField(default='wip', max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email_address', models.CharField(blank=True, max_length=255)),
                ('personal_phone_number', models.CharField(blank=True, max_length=255)),
                ('home_phone_number', models.CharField(blank=True, max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=255)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urec_app.accidentticket')),
            ],
        ),
    ]
