# Generated by Django 4.1.2 on 2022-12-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urec_app', '0004_rename_ticket_id_accidentticketcontactinfo_accident_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident_Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time_submission', models.DateTimeField(auto_now_add=True)),
                ('urec_facility', models.CharField(max_length=255)),
                ('location_in_facility', models.CharField(max_length=255)),
                ('activity_causing_injury', models.CharField(max_length=255)),
                ('staff_netid', models.CharField(default='tst123', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Accident_Ticket_Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(max_length=255)),
                ('injury_description', models.CharField(max_length=1023)),
                ('accident_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urec_app.accidentticket')),
            ],
        ),
        migrations.CreateModel(
            name='Accident_Ticket_Contact_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_relation', models.CharField(default='wip', max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email_address', models.CharField(blank=True, max_length=255)),
                ('personal_phone_number', models.CharField(blank=True, max_length=255)),
                ('home_phone_number', models.CharField(blank=True, max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=255)),
                ('accident_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urec_app.accidentticket')),
            ],
        ),
    ]
