# Generated by Django 4.1.2 on 2022-12-06 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urec_app', '0006_alter_accident_ticket_contact_info_accident_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident_Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time_submission', models.DateTimeField(auto_now_add=True)),
                ('urec_facility', models.CharField(max_length=255)),
                ('location_in_facility', models.CharField(max_length=255)),
                ('activity_during_incident', models.CharField(max_length=255)),
                ('staff_netid', models.CharField(default='tst123', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='accident_ticket_injury',
            name='care_provided',
            field=models.CharField(default='', max_length=1023),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Incident_Ticket_Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_nature', models.CharField(max_length=255)),
                ('incident_description', models.CharField(max_length=1023)),
                ('action_taken', models.CharField(max_length=1023)),
                ('incident_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urec_app.incident_ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Incident_Ticket_Contact_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email_address', models.CharField(blank=True, max_length=255)),
                ('personal_phone_number', models.CharField(blank=True, max_length=255)),
                ('home_phone_number', models.CharField(blank=True, max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=255)),
                ('minor_status', models.CharField(max_length=255)),
                ('incident_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urec_app.incident_ticket')),
            ],
        ),
    ]
