# Generated by Django 4.1.2 on 2022-12-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urec_app', '0007_incident_ticket_accident_ticket_injury_care_provided_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_description', models.CharField(blank=True, max_length=255)),
                ('date_time_due', models.DateTimeField()),
                ('text_input_required', models.BooleanField(default=False)),
                ('optional_text', models.CharField(blank=True, max_length=255)),
                ('task_completion', models.BooleanField(default=False)),
                ('date_time_completion', models.DateTimeField(auto_now_add=True)),
                ('staff_netid', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
