# Generated by Django 4.1.2 on 2022-12-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urec_app', '0009_alter_task_date_time_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_time_completion',
            field=models.DateTimeField(blank=True),
        ),
    ]
