# Generated by Django 4.1.2 on 2022-12-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urec_app', '0015_alter_accident_ticket_contact_info_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('count_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time_submission', models.DateTimeField(auto_now_add=True)),
                ('location_in_facility', models.CharField(choices=[('Facility 1', (('Location 1', 'Location 1'), ('Location 2', 'Location 2'), ('Location 3', 'Location 3'))), ('Facility 2', (('Location 4', 'Location 4'), ('Location 5', 'Location 5'), ('Location 6', 'Location 6'))), ('Facility 3', (('Location 7', 'Location 7'), ('Location 8', 'Location 8'), ('Location 9', 'Location 9')))], max_length=255)),
                ('location_count', models.SmallIntegerField()),
                ('staff_netid', models.CharField(default='tst123', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='incident_ticket_contact_info',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='incident_ticket_incident',
            name='action_taken',
            field=models.TextField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='incident_ticket_incident',
            name='incident_description',
            field=models.TextField(max_length=1023),
        ),
    ]
